# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='EMail',
        ),
        migrations.RemoveField(
            model_name='site',
            name='department',
        ),
        migrations.AddField(
            model_name='site',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='EMail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='EMail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='street2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='site',
            name='street1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='street2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='Due_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, default="blank", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_do',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
