# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170502_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('a', 'Completed'), ('c', 'Cancelled')], default='n', max_length=1),
        ),
    ]
